export const SCROLLBAR_CONSTANTS = {
  MAX_FRAME_MODULO: 10,
  FIRST_STEP_BAR: 3,
  FIRST_STEP_BUTTON: 1,
  TICKS_OUTSIDE_RANGE: 5,

  MARGINS: {
    SCROLL: 16,
    THUMB: 3,
    MINIMUM_LENGTH: 14,
  },
} as const;
