// Copyright (c) Heribert Gasparoli Private. All rights reserved.

export const SCHEDULING_CONSTANTS = {
  SUCCESS_COVERAGE_THRESHOLD: 0.8,
  CANCELLATION_CHECK_INTERVAL_MS: 100,
  RANDOM_ASSIGNMENT_PROBABILITY: 0.7,
  OVERTIME_THRESHOLD_FACTOR: 1.2,
  LOW_MOTIVATION_THRESHOLD: 0.2,
  FAIRNESS_MAX_DEVIATION_RATIO: 0.5,
  YIELD_INTERVAL_GENERATIONS: 10,
  TOURNAMENT_SIZE: 3,
} as const;

export const AGENT_STATE_CONSTANTS = {
  HUNGER_WEIGHT: 0.6,
  GREED_WEIGHT: 0.3,
  SATIETY_WEIGHT: 0.1,
  FREQUENCY_WEIGHT: 0.4,
  RECENCY_WEIGHT: 0.3,
  SATISFACTION_WEIGHT: 0.3,
  MAX_SEVERITY_WEIGHT: 0.7,
  AVG_SEVERITY_WEIGHT: 0.3,
  MAX_FREQUENCY_COUNT: 10,
  SATISFACTION_INCREMENT: 0.05,
  DEFAULT_SATISFACTION: 0.5,
  DEFAULT_MOTIVATION: 0.5,
  TIME_PRESSURE_MIDPOINT: 0.5,
  RECENCY_THRESHOLD_DAYS_7: 7,
  RECENCY_THRESHOLD_DAYS_14: 14,
  RECENCY_THRESHOLD_DAYS_30: 30,
  RECENCY_FACTOR_SHORT: 0.3,
  RECENCY_FACTOR_MEDIUM: 0.6,
} as const;

export const EVOLUTION_CONSTANTS = {
  MUTATION_SWAP_THRESHOLD: 0.25,
  MUTATION_REMOVE_THRESHOLD: 0.40,
  MUTATION_REPAIR_THRESHOLD: 0.70,
  GREEDY_SHUFFLE_FACTOR: 0.3,
  CROSSOVER_SWAP_PROBABILITY: 0.5,
  GREEDY_HOUR_DEFICIT_WEIGHT: 2,
  GREEDY_MOTIVATION_WEIGHT: 10,
  PROGRESS_REPORT_INTERVAL: 5,
  CONVERGENCE_HISTORY_SIZE: 10,
  MS_PER_HOUR: 1000 * 60 * 60,
  MS_PER_DAY: 1000 * 60 * 60 * 24,
  RNG_MULTIPLIER: 1664525,
  RNG_INCREMENT: 1013904223,
  RNG_MODULUS: 4294967296,
  ID_RANDOM_RANGE: 10000,
  GREEDY_BLOCK_CONSISTENCY_WEIGHT: 5,
} as const;
