export class ConstantKeys {
  public static BACKGROUND_COLOR_KEY = 'BACKGROUND_COLOR_KEY';
  public static BACKGROUND_COLOR_SATURDAY_KEY = 'BACKGROUND_COLOR_SATURDAY_KEY';
  public static BACKGROUND_COLOR_SUNDAY_KEY = 'BACKGROUND_COLOR_SUNDAY_KEY';
  public static BACKGROUND_COLOR_HOLIDAY_KEY = 'BACKGROUND_COLOR_HOLIDAY_KEY';
  public static BACKGROUND_COLOR_OFFICIALLY_KEY =
    'BACKGROUND_COLOR_OFFICIALLY_KEY';
  public static BORDER_COLOR_KEY = 'BORDER_COLOR_KEY';
  public static MAIN_TEXT_COLOR_KEY = 'MAIN_TEXT_COLOR_KEY';
  public static SUB_TEXT_COLOR_KEY = 'SUB_TEXT_COLOR_KEY';
  public static EVEN_MONTH_COLOR_KEY = 'EVEN_MONTH_COLOR_KEY';
  public static ODD_MONTH_COLOR_KEY = 'ODD_MONTH_COLOR_KEY';

  public static FOREGROUND_COLOR_KEY = 'FOREGROUND_COLOR_KEY';
  public static CONTROL_BACKGROUND_COLOR_KEY = 'CONTROL_BACKGROUND_COLOR_KEY';
  public static HEADER_BACKGROUND_COLOR_KEY = 'HEADER_BACKGROUND_COLOR_KEY';
  public static HEADER_FOREGROUND_COLOR_KEY = 'HEADER_FOREGROUND_COLOR_KEY';
  public static FOCUS_BORDER_COLOR_KEY = 'FOCUS_BORDER_COLOR_KEY';
  public static BORDER_END_MONTH_COLOR_KEY = 'BORDER_END_MONTH_COLOR_KEY';

  public static MAIN_FONT_NAME_KEY = 'MAIN_FONT_NAME_KEY';
  public static FIRST_SUB_FONT_NAME_KEY = 'FIRST_SUB_FONT_NAME_KEY';
  public static SECOND_SUB_FONT_NAME_KEY = 'SECOND_SUB_FONT_NAME_KEY';

  public static MAIN_FONT_SIZE_KEY = 'MAIN_FONT_SIZE_KEY';
  public static FIRST_SUB_FONT_SIZE_KEY = 'FIRST_SUB_FONT_SIZE_KEY';
  public static SECOND_SUB_FONT_SIZE_KEY = 'SECOND_SUB_FONT_SIZE_KEY';
}
