// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/**
 * Writes the build identity of a UI build. Mode "source" writes src/build-info.ts before ng build, so
 * the bundle knows which build it is; mode "dist" writes dist/klacks.ui/browser/version.json after
 * ng build, so open tabs can see which build is deployed. Both read the same environment variables:
 * KLACKS_VERSION (release version without "v", default 0.0.0) and KLACKS_BUILD_KEY (git SHA, default
 * "dev", which disables the stale-tab check). Values are validated because they end up in TypeScript.
 * Usage: npx tsx tools/write-build-info.ts <source|dist>
 * @param mode - First command line argument: "source" or "dist"
 */
import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { DEV_BUILD_KEY, DEV_BUILD_VERSION } from '../src/app/domain/constants/build-info.constants';

interface IBuildIdentity {
  version: string;
  buildKey: string;
}

const ROOT_DIRECTORY = resolve(__dirname, '..');
const SOURCE_FILE = resolve(ROOT_DIRECTORY, 'src', 'build-info.ts');
const DIST_DIRECTORY = resolve(ROOT_DIRECTORY, 'dist', 'klacks.ui', 'browser');
const DIST_FILE = resolve(DIST_DIRECTORY, 'version.json');
const VERSION_PATTERN = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;
const BUILD_KEY_PATTERN = /^[0-9A-Za-z._-]{1,64}$/;
const MODE_SOURCE = 'source';
const MODE_DIST = 'dist';

function readBuildIdentity(): IBuildIdentity {
  const version = process.env['KLACKS_VERSION'] || DEV_BUILD_VERSION;
  const buildKey = process.env['KLACKS_BUILD_KEY'] || DEV_BUILD_KEY;
  if (!VERSION_PATTERN.test(version)) {
    throw new Error(`KLACKS_VERSION "${version}" is not a release version like 1.0.28`);
  }
  if (!BUILD_KEY_PATTERN.test(buildKey)) {
    throw new Error(`KLACKS_BUILD_KEY "${buildKey}" must be 1-64 characters of letters, digits, ".", "_" and "-"`);
  }
  return { version, buildKey };
}

function sourceFileContent({ version, buildKey }: IBuildIdentity): string {
  return [
    '// Copyright (c) Heribert Gasparoli Private. All rights reserved.',
    '',
    '/**',
    ' * Build identity compiled into this bundle. Generated by tools/write-build-info.ts in the Docker',
    ' * build; the committed values mark a development build, which disables the stale-tab version check.',
    ' */',
    "import { IBuildInfo } from './app/domain/interfaces/build-info.interface';",
    '',
    'export const BUILD_INFO_VALUE: IBuildInfo = {',
    `  version: '${version}',`,
    `  buildKey: '${buildKey}',`,
    '};',
    '',
  ].join('\n');
}

function writeSource(identity: IBuildIdentity): void {
  writeFileSync(SOURCE_FILE, sourceFileContent(identity), 'utf8');
  console.log(`build-info: wrote ${SOURCE_FILE} (${identity.version}, ${identity.buildKey})`);
}

function writeDist(identity: IBuildIdentity): void {
  if (!existsSync(DIST_DIRECTORY)) {
    throw new Error(`${DIST_DIRECTORY} does not exist - run ng build first`);
  }
  writeFileSync(DIST_FILE, `${JSON.stringify(identity)}\n`, 'utf8');
  console.log(`build-info: wrote ${DIST_FILE} (${identity.version}, ${identity.buildKey})`);
}

const mode = process.argv[2];
const identity = readBuildIdentity();
if (mode === MODE_SOURCE) {
  writeSource(identity);
} else if (mode === MODE_DIST) {
  writeDist(identity);
} else {
  throw new Error(`Unknown mode "${mode}" - use "${MODE_SOURCE}" or "${MODE_DIST}"`);
}
