// Copyright (c) Heribert Gasparoli Private. All rights reserved.

/**
 * Build identity compiled into this bundle. Generated by tools/write-build-info.ts in the Docker
 * build; the committed values mark a development build, which disables the stale-tab version check.
 */
import { IBuildInfo } from './app/domain/interfaces/build-info.interface';

export const BUILD_INFO_VALUE: IBuildInfo = {
  version: '0.0.0',
  buildKey: 'dev',
};
