// Copyright (c) Heribert Gasparoli. SPDX-License-Identifier: AGPL-3.0-only

/**
 * Real route-PDF labels of all 25 Klacks languages (copied from the core i18n files and the language plugin
 * translations.json), used to prove that every language renders in jsPDF without missing glyphs.
 */

export const PDF_SAMPLE_LANGUAGES = [
  'de',
  'en',
  'fr',
  'it',
  'ar',
  'ja',
  'cs',
  'da',
  'el',
  'es',
  'fi',
  'he',
  'id',
  'ko',
  'ms',
  'nb',
  'nl',
  'pl',
  'pt',
  'ro',
  'sv',
  'th',
  'vi',
  'zh-CN',
  'zh-TW',
] as const;

export type PdfSampleLanguage = (typeof PDF_SAMPLE_LANGUAGES)[number];

export const PDF_ROUTE_LABELS: Readonly<Record<PdfSampleLanguage, Readonly<Record<string, string>>>> = {
  de: {
    'generated': "Erstellt",
    'route-summary': "Routenübersicht",
    'start-base': "Startpunkt",
    'end-base': "Endpunkt",
    'total-distance': "Gesamtdistanz",
    'total-travel-time': "Gesamtfahrzeit",
    'route-details': "Routendetails",
    'location': "Standort",
    'arrival': "Ankunft",
    'departure': "Abfahrt",
    'travel-time': "Fahrzeit",
    'distance': "Distanz",
    'page': "Seite",
    'of': "von",
    'directions': "Wegbeschreibung",
    'no-directions-available': "Keine detaillierten Wegbeschreibungen verfügbar",
  },
  en: {
    'generated': "Generated",
    'route-summary': "Route Summary",
    'start-base': "Start Base",
    'end-base': "End Base",
    'total-distance': "Total Distance",
    'total-travel-time': "Total Travel Time",
    'route-details': "Route Details",
    'location': "Location",
    'arrival': "Arrival",
    'departure': "Departure",
    'travel-time': "Travel Time",
    'distance': "Distance",
    'page': "Page",
    'of': "of",
    'directions': "Directions",
    'no-directions-available': "No detailed directions available",
  },
  fr: {
    'generated': "Généré",
    'route-summary': "Résumé de l'itinéraire",
    'start-base': "Point de départ",
    'end-base': "Point d'arrivée",
    'total-distance': "Distance totale",
    'total-travel-time': "Temps de trajet total",
    'route-details': "Détails de l'itinéraire",
    'location': "Lieu",
    'arrival': "Arrivée",
    'departure': "Départ",
    'travel-time': "Temps de trajet",
    'distance': "Distance",
    'page': "Page",
    'of': "de",
    'directions': "Itinéraire",
    'no-directions-available': "Aucune indication détaillée disponible",
  },
  it: {
    'generated': "Generato",
    'route-summary': "Riepilogo percorso",
    'start-base': "Punto di partenza",
    'end-base': "Punto di arrivo",
    'total-distance': "Distanza totale",
    'total-travel-time': "Tempo di viaggio totale",
    'route-details': "Dettagli percorso",
    'location': "Posizione",
    'arrival': "Arrivo",
    'departure': "Partenza",
    'travel-time': "Tempo di viaggio",
    'distance': "Distanza",
    'page': "Pagina",
    'of': "di",
    'directions': "Indicazioni stradali",
    'no-directions-available': "Nessuna indicazione dettagliata disponibile",
  },
  ar: {
    'generated': "تم الإنشاء",
    'route-summary': "ملخص المسار",
    'start-base': "نقطة البداية",
    'end-base': "نقطة النهاية",
    'total-distance': "المسافة الإجمالية",
    'total-travel-time': "وقت السفر الإجمالي",
    'route-details': "تفاصيل المسار",
    'location': "الموقع",
    'arrival': "الوصول",
    'departure': "المغادرة",
    'travel-time': "وقت السفر",
    'distance': "المسافة",
    'page': "صفحة",
    'of': "من",
    'directions': "الاتجاهات",
    'no-directions-available': "لا تتوفر اتجاهات تفصيلية",
  },
  ja: {
    'generated': "作成日",
    'route-summary': "ルート概要",
    'start-base': "出発拠点",
    'end-base': "到着拠点",
    'total-distance': "総距離",
    'total-travel-time': "総移動時間",
    'route-details': "ルート詳細",
    'location': "場所",
    'arrival': "到着",
    'departure': "出発",
    'travel-time': "移動時間",
    'distance': "距離",
    'page': "ページ",
    'of': "/",
    'directions': "経路案内",
    'no-directions-available': "詳細な経路案内はありません",
  },
  cs: {
    'generated': "Vytvořeno",
    'route-summary': "Přehled trasy",
    'start-base': "Výchozí bod",
    'end-base': "Cílový bod",
    'total-distance': "Celková vzdálenost",
    'total-travel-time': "Celková doba jízdy",
    'route-details': "Detail trasy",
    'location': "Místo",
    'arrival': "Příjezd",
    'departure': "Odjezd",
    'travel-time': "Doba jízdy",
    'distance': "Vzdálenost",
    'page': "Stránka",
    'of': "z",
    'directions': "Popis trasy",
    'no-directions-available': "Podrobný popis trasy není k dispozici",
  },
  da: {
    'generated': "Oprettet",
    'route-summary': "Ruteoversigt",
    'start-base': "Startpunkt",
    'end-base': "Slutpunkt",
    'total-distance': "Samlet distance",
    'total-travel-time': "Samlet rejsetid",
    'route-details': "Rutedetaljer",
    'location': "Lokation",
    'arrival': "Ankomst",
    'departure': "Afgang",
    'travel-time': "Rejsetid",
    'distance': "Distance",
    'page': "Side",
    'of': "af",
    'directions': "Vejbeskrivelse",
    'no-directions-available': "Ingen detaljerede vejbeskrivelser tilgængelige",
  },
  el: {
    'generated': "Δημιουργήθηκε",
    'route-summary': "Επισκόπηση διαδρομής",
    'start-base': "Σημείο εκκίνησης",
    'end-base': "Σημείο τερματισμού",
    'total-distance': "Συνολική απόσταση",
    'total-travel-time': "Συνολικός χρόνος ταξιδιού",
    'route-details': "Λεπτομέρειες διαδρομής",
    'location': "Τοποθεσία",
    'arrival': "Άφιξη",
    'departure': "Αναχώρηση",
    'travel-time': "Χρόνος ταξιδιού",
    'distance': "Απόσταση",
    'page': "Σελίδα",
    'of': "από",
    'directions': "Οδηγίες",
    'no-directions-available': "Δεν υπάρχουν διαθέσιμες λεπτομερείς οδηγίες",
  },
  es: {
    'generated': "Generado",
    'route-summary': "Resumen de ruta",
    'start-base': "Punto de inicio",
    'end-base': "Punto final",
    'total-distance': "Distancia total",
    'total-travel-time': "Tiempo total de viaje",
    'route-details': "Detalles de ruta",
    'location': "Ubicación",
    'arrival': "Llegada",
    'departure': "Salida",
    'travel-time': "Tiempo de viaje",
    'distance': "Distancia",
    'page': "Página",
    'of': "de",
    'directions': "Indicaciones",
    'no-directions-available': "No hay indicaciones detalladas disponibles",
  },
  fi: {
    'generated': "Luotu",
    'route-summary': "Reittikooste",
    'start-base': "Lähtöpiste",
    'end-base': "Päätepiste",
    'total-distance': "Kokonaismatka",
    'total-travel-time': "Kokonaismatka-aika",
    'route-details': "Reittitiedot",
    'location': "Sijainti",
    'arrival': "Saapuminen",
    'departure': "Lähtö",
    'travel-time': "Matka-aika",
    'distance': "Etäisyys",
    'page': "Sivu",
    'of': "/",
    'directions': "Reittiohjeet",
    'no-directions-available': "Yksityiskohtaisia reittiohjeita ei ole saatavilla",
  },
  he: {
    'generated': "נוצר",
    'route-summary': "סיכום מסלול",
    'start-base': "נקודת התחלה",
    'end-base': "נקודת סיום",
    'total-distance': "מרחק כולל",
    'total-travel-time': "זמן נסיעה כולל",
    'route-details': "פרטי מסלול",
    'location': "מיקום",
    'arrival': "הגעה",
    'departure': "יציאה",
    'travel-time': "זמן נסיעה",
    'distance': "מרחק",
    'page': "עמוד",
    'of': "מתוך",
    'directions': "הוראות נסיעה",
    'no-directions-available': "אין הוראות נסיעה מפורטות",
  },
  id: {
    'generated': "Dibuat",
    'route-summary': "Ringkasan rute",
    'start-base': "Titik awal",
    'end-base': "Titik akhir",
    'total-distance': "Jarak total",
    'total-travel-time': "Waktu perjalanan total",
    'route-details': "Detail rute",
    'location': "Lokasi",
    'arrival': "Kedatangan",
    'departure': "Keberangkatan",
    'travel-time': "Waktu perjalanan",
    'distance': "Jarak",
    'page': "Halaman",
    'of': "dari",
    'directions': "Petunjuk arah",
    'no-directions-available': "Tidak ada petunjuk arah detail tersedia",
  },
  ko: {
    'generated': "생성일",
    'route-summary': "경로 요약",
    'start-base': "출발지",
    'end-base': "도착지",
    'total-distance': "총 거리",
    'total-travel-time': "총 이동 시간",
    'route-details': "경로 상세",
    'location': "위치",
    'arrival': "도착",
    'departure': "출발",
    'travel-time': "이동 시간",
    'distance': "거리",
    'page': "페이지",
    'of': "/",
    'directions': "경로 안내",
    'no-directions-available': "상세 경로 안내를 사용할 수 없습니다",
  },
  ms: {
    'generated': "Dijana",
    'route-summary': "Ringkasan laluan",
    'start-base': "Titik permulaan",
    'end-base': "Titik akhir",
    'total-distance': "Jumlah jarak",
    'total-travel-time': "Jumlah masa perjalanan",
    'route-details': "Butiran laluan",
    'location': "Lokasi",
    'arrival': "Ketibaan",
    'departure': "Berlepas",
    'travel-time': "Masa perjalanan",
    'distance': "Jarak",
    'page': "Halaman",
    'of': "daripada",
    'directions': "Arah perjalanan",
    'no-directions-available': "Tiada arahan perjalanan terperinci tersedia",
  },
  nb: {
    'generated': "Opprettet",
    'route-summary': "Ruteoversikt",
    'start-base': "Startpunkt",
    'end-base': "Sluttpunkt",
    'total-distance': "Total avstand",
    'total-travel-time': "Total reisetid",
    'route-details': "Rutedetaljer",
    'location': "Lokasjon",
    'arrival': "Ankomst",
    'departure': "Avgang",
    'travel-time': "Reisetid",
    'distance': "Avstand",
    'page': "Side",
    'of': "av",
    'directions': "Veibeskrivelse",
    'no-directions-available': "Ingen detaljerte veibeskrivelser tilgjengelig",
  },
  nl: {
    'generated': "Aangemaakt",
    'route-summary': "Route-overzicht",
    'start-base': "Startpunt",
    'end-base': "Eindpunt",
    'total-distance': "Totale afstand",
    'total-travel-time': "Totale reistijd",
    'route-details': "Route-details",
    'location': "Locatie",
    'arrival': "Aankomst",
    'departure': "Vertrek",
    'travel-time': "Reistijd",
    'distance': "Afstand",
    'page': "Pagina",
    'of': "van",
    'directions': "Routebeschrijving",
    'no-directions-available': "Geen gedetailleerde routebeschrijvingen beschikbaar",
  },
  pl: {
    'generated': "Wygenerowano",
    'route-summary': "Podsumowanie trasy",
    'start-base': "Punkt startowy",
    'end-base': "Punkt końcowy",
    'total-distance': "Całkowita odległość",
    'total-travel-time': "Całkowity czas podróży",
    'route-details': "Szczegóły trasy",
    'location': "Lokalizacja",
    'arrival': "Przyjazd",
    'departure': "Odjazd",
    'travel-time': "Czas podróży",
    'distance': "Odległość",
    'page': "Strona",
    'of': "z",
    'directions': "Wskazówki dojazdu",
    'no-directions-available': "Brak szczegółowych wskazówek dojazdu",
  },
  pt: {
    'generated': "Gerado",
    'route-summary': "Resumo da rota",
    'start-base': "Ponto de partida",
    'end-base': "Ponto de chegada",
    'total-distance': "Distância total",
    'total-travel-time': "Tempo total de viagem",
    'route-details': "Detalhes da rota",
    'location': "Localização",
    'arrival': "Chegada",
    'departure': "Partida",
    'travel-time': "Tempo de viagem",
    'distance': "Distância",
    'page': "Página",
    'of': "de",
    'directions': "Direções",
    'no-directions-available': "Sem direções detalhadas disponíveis",
  },
  ro: {
    'generated': "Generat",
    'route-summary': "Rezumat traseu",
    'start-base': "Punct de plecare",
    'end-base': "Punct de sosire",
    'total-distance': "Distanță totală",
    'total-travel-time': "Timp total de deplasare",
    'route-details': "Detalii traseu",
    'location': "Locație",
    'arrival': "Sosire",
    'departure': "Plecare",
    'travel-time': "Timp deplasare",
    'distance': "Distanță",
    'page': "Pagină",
    'of': "din",
    'directions': "Indicații de orientare",
    'no-directions-available': "Nu există indicații detaliate disponibile",
  },
  sv: {
    'generated': "Skapad",
    'route-summary': "Ruttöversikt",
    'start-base': "Startpunkt",
    'end-base': "Slutpunkt",
    'total-distance': "Total distans",
    'total-travel-time': "Total restid",
    'route-details': "Ruttdetaljer",
    'location': "Plats",
    'arrival': "Ankomst",
    'departure': "Avgång",
    'travel-time': "Restid",
    'distance': "Distans",
    'page': "Sida",
    'of': "av",
    'directions': "Vägbeskrivning",
    'no-directions-available': "Inga detaljerade vägbeskrivningar tillgängliga",
  },
  th: {
    'generated': "สร้างเมื่อ",
    'route-summary': "สรุปเส้นทาง",
    'start-base': "จุดเริ่มต้น",
    'end-base': "จุดสิ้นสุด",
    'total-distance': "ระยะทางทั้งหมด",
    'total-travel-time': "เวลาเดินทางทั้งหมด",
    'route-details': "รายละเอียดเส้นทาง",
    'location': "สถานที่",
    'arrival': "ถึง",
    'departure': "ออก",
    'travel-time': "เวลาเดินทาง",
    'distance': "ระยะทาง",
    'page': "หน้า",
    'of': "จาก",
    'directions': "เส้นทาง",
    'no-directions-available': "ไม่มีเส้นทางรายละเอียด",
  },
  vi: {
    'generated': "Đã tạo",
    'route-summary': "Tổng quan tuyến đường",
    'start-base': "Điểm xuất phát",
    'end-base': "Điểm đến",
    'total-distance': "Tổng khoảng cách",
    'total-travel-time': "Tổng thời gian di chuyển",
    'route-details': "Chi tiết tuyến đường",
    'location': "Địa điểm",
    'arrival': "Đến",
    'departure': "Đi",
    'travel-time': "Thời gian di chuyển",
    'distance': "Khoảng cách",
    'page': "Trang",
    'of': "trong",
    'directions': "Chỉ đường",
    'no-directions-available': "Không có chỉ đường chi tiết",
  },
  'zh-CN': {
    'generated': "生成于",
    'route-summary': "路线概览",
    'start-base': "起点",
    'end-base': "终点",
    'total-distance': "总距离",
    'total-travel-time': "总行程时间",
    'route-details': "路线详情",
    'location': "位置",
    'arrival': "到达",
    'departure': "出发",
    'travel-time': "行程时间",
    'distance': "距离",
    'page': "页",
    'of': "共",
    'directions': "路线说明",
    'no-directions-available': "无详细路线说明",
  },
  'zh-TW': {
    'generated': "生成於",
    'route-summary': "路線概覽",
    'start-base': "起點",
    'end-base': "終點",
    'total-distance': "總距離",
    'total-travel-time': "總行程時間",
    'route-details': "路線詳情",
    'location': "位置",
    'arrival': "到達",
    'departure': "出發",
    'travel-time': "行程時間",
    'distance': "距離",
    'page': "頁",
    'of': "共",
    'directions': "路線說明",
    'no-directions-available': "無詳細路線說明",
  },
};
